module(...)

-- This file is for use with Love2d and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getFrames()
	local frames = {
		
			{
				name = "background_1",
				rect = { x = 54, y = 78, width = 16, height = 16 }, 
			},
		
			{
				name = "chest",
				rect = { x = 2, y = 108, width = 16, height = 16 }, 
			},
		
			{
				name = "door_closed",
				rect = { x = 2, y = 72, width = 16, height = 16 }, 
			},
		
			{
				name = "door_open",
				rect = { x = 20, y = 70, width = 16, height = 16 }, 
			},
		
			{
				name = "empty",
				rect = { x = 2, y = 90, width = 16, height = 16 }, 
			},
		
			{
				name = "flaming_skull",
				rect = { x = 34, y = 2, width = 16, height = 21 }, 
			},
		
			{
				name = "goblin",
				rect = { x = 34, y = 25, width = 16, height = 18 }, 
			},
		
			{
				name = "golem",
				rect = { x = 2, y = 2, width = 30, height = 32 }, 
			},
		
			{
				name = "green_door_closed.png",
				rect = { x = 20, y = 106, width = 16, height = 16 }, 
			},
		
			{
				name = "green_door_open.png",
				rect = { x = 54, y = 96, width = 16, height = 16 }, 
			},
		
			{
				name = "half_blue",
				rect = { x = 54, y = 42, width = 16, height = 16 }, 
			},
		
			{
				name = "half_red",
				rect = { x = 2, y = 36, width = 16, height = 16 }, 
			},
		
			{
				name = "ladder.png",
				rect = { x = 38, y = 65, width = 14, height = 16 }, 
			},
		
			{
				name = "mushroom",
				rect = { x = 54, y = 60, width = 16, height = 16 }, 
			},
		
			{
				name = "player",
				rect = { x = 66, y = 114, width = 8, height = 16 }, 
			},
		
			{
				name = "player_man_standing",
				rect = { x = 52, y = 22, width = 8, height = 18 }, 
			},
		
			{
				name = "player_man_walk_1",
				rect = { x = 20, y = 36, width = 12, height = 18 }, 
			},
		
			{
				name = "player_man_walk_2",
				rect = { x = 52, y = 2, width = 8, height = 18 }, 
			},
		
			{
				name = "player_man_walk_3",
				rect = { x = 34, y = 45, width = 8, height = 18 }, 
			},
		
			{
				name = "player_man_walk_4",
				rect = { x = 62, y = 2, width = 8, height = 18 }, 
			},
		
			{
				name = "player_man_walk_5",
				rect = { x = 44, y = 45, width = 8, height = 18 }, 
			},
		
			{
				name = "player_man_walk_6",
				rect = { x = 62, y = 22, width = 8, height = 18 }, 
			},
		
			{
				name = "player_old",
				rect = { x = 54, y = 114, width = 10, height = 16 }, 
			},
		
			{
				name = "slime_blue_1",
				rect = { x = 38, y = 97, width = 14, height = 12 }, 
			},
		
			{
				name = "slime_blue_2",
				rect = { x = 20, y = 124, width = 16, height = 10 }, 
			},
		
			{
				name = "slime_blue_3",
				rect = { x = 20, y = 56, width = 12, height = 12 }, 
			},
		
			{
				name = "slime_green_1",
				rect = { x = 38, y = 83, width = 14, height = 12 }, 
			},
		
			{
				name = "slime_green_2",
				rect = { x = 2, y = 126, width = 16, height = 10 }, 
			},
		
			{
				name = "slime_green_3",
				rect = { x = 20, y = 136, width = 12, height = 12 }, 
			},
		
			{
				name = "slime_red_1",
				rect = { x = 38, y = 111, width = 14, height = 12 }, 
			},
		
			{
				name = "slime_red_2",
				rect = { x = 2, y = 138, width = 16, height = 10 }, 
			},
		
			{
				name = "slime_red_3",
				rect = { x = 38, y = 125, width = 12, height = 12 }, 
			},
		
			{
				name = "wall_1.png",
				rect = { x = 20, y = 88, width = 16, height = 16 }, 
			},
		
			{
				name = "wall_dirt.png",
				rect = { x = 2, y = 54, width = 16, height = 16 }, 
			},
		
	}

	return frames
end